import { Router } from 'express';
import { buscar, guardar, show, actualizar, eliminar } from '../controllers/control_clientes';
import { checkAuth } from '../Middleware/check-auth';
const router = Router();
router.get("/buscar/:nombres", checkAuth, buscar);
router.post("/", checkAuth, guardar);
router.get("/show/:IdUsuario", checkAuth, show);
router.post("/actualizar/:id", checkAuth, actualizar);
router.delete("/eliminar/:id", checkAuth, eliminar);
export default router;